<div class="col-lg-12">
        <div class="panel panel-default">
          <div class="panel-heading">User profile</div>
          <div class="panel-body">
            <a href="<?php echo URL_ROOT;?>/profiles/add"
            class="btn btn-primary">New</a>
              <table data-toggle="table" data-url=""  data-show-refresh="true" data-show-toggle="true" 
              data-show-columns="true" data-search="true" data-select-item-name="toolbar1" data-pagination="true" 
              data-sort-name="name" data-sort-order="desc">
              <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Profile name</th>
                                            <th>Options</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach ($data['profiles'] as $profiles) :?>
                                        <tr>
                                            <td><?= $profiles->id; ?> </td>
                                            <td><?= $profiles->profile_name; ?></td>
                                            <td>
                                            <div class="card-footer">
                                            <a href="<?= URL_ROOT;?>/profiles/edit/<?= $profiles->id?>"
            								                class="btn btn-primary">Modifier</a>
                                            <form action="<?= URL_ROOT;?>/profiles/delete/<?= $profiles->id; ?>" method="post">
                                            <button type="submit" onclick="return confirm('Are sure you want to delete this profile ?')" class="btn btn-danger btn-sm">Delete</button>
                                            </form>
                                            </div>
                                            </td>
                                        </tr>
                                        <?php endforeach;?>
                                    </tbody>
              </table>
          </div>
        </div>
      </div>
