	
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
				<li class="active"><?= SITE_NAME; ?> / Add user</li>
			</ol>
		</div><!--/.row-->
		<!-- 
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Gestion des courriers</h1>
			</div>
		</div> <row-->
				
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">Add user</div>
					<div class="panel-body">
						<div class="col-md-6">
							<form role="form" action="<?= URL_ROOT; ?>/users/add" method="post" enctype="multipart/form-data">
								
								<div class="form-group">
									<label>Profil :</label>
									<select name="fk_profile_id" class="form-control <?= (!empty($data['fk_profile_id_err'])) ? 'is-invalid' : ''; ?>">
										<option value=""></option>		
										<?php foreach ($data['profile'] as $profile) : ?>	
										<option value="<?php echo $profile->fk_profile_id;?>"><?php echo $profile->profile_name;?></option>	
										<?php endforeach;?>
									</select>
									<span class="invalid-feedback"><?= $data['fk_profile_id_err'] ?></span>
								</div>
								<div class="form-group">
								<label>Username :</label>
									<input type="text" name="username" class="form-control <?= (!empty($data['username_err'])) ? 'is-invalid' : ''; ?>" 
									placeholder="" value="<?= $data['username']; ?>">
									<span class="invalid-feedback"><?= $data['username_err'] ?></span>
								</div>	
								<div class="form-group">	
									<label>Mot de passe :</label>
									<input type="password" name="pwd" class="form-control <?= (!empty($data['pwd_err'])) ? 'is-invalid' : ''; ?>" 
									placeholder="" value="<?= $data['pwd']; ?>">
									<span class="invalid-feedback"><?= $data['pwd_err'] ?></span>
								</div>
								<div class="form-group">	
									<label>Confirmer mot de passe</label>
									<input type="password" name="confirm_pwd" class="form-control <?= (!empty($data['confirm_pwd_err'])) ? 'is_invalid' : '';  ?>" 
									placeholder="" value="<?= $data['confirm_pwd']; ?>">
									<span class="invalid-feedback"><?= $data['confirm_pwd_err'] ?></span>
								</div>
								<button type="submit" id="submit" class="btn btn-primary">Valider</button>
								<button type="reset" onclick="closed()" class="btn btn-default">Fermer</button>
							</form>
							</div>
						</div>
				</div>
			</div><!-- /.col-->
<script>
	function closed()
	{
		window.opener.location.reload();
		window.close();
	}
</script>