<div class="col-lg-12">
        <div class="panel panel-default">
          <div class="panel-heading">Gestion des utilisateurs</div>
          <div class="panel-body">
            <a href='javascript:PopupCentrer("<?php echo URL_ROOT;?>/users/add",500,750,"menubar=no,scrollbars=no,statusbar=no")'
            class="btn btn-primary">Nouveau</a>
              <table data-toggle="table" data-url=""  data-show-refresh="true" data-show-toggle="true"
              data-show-columns="true" data-search="true" data-select-item-name="toolbar1" data-pagination="true"
              data-sort-name="name" data-sort-order="desc">
              <thead>
                                        <tr>
                                            <th>Nom</th>
                                            <th>Prenom</th>
                                            <th>Nom d'utilisateur</th>
                                            <th>Email</th>
                                            <th>Date enregistre</th>
                                            <th>Options</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach ($data['users'] as $user) :?>
                                        <tr>
                                            <td><?= $user->nom; ?> </td>
                                            <td><?= $user->prenom; ?></td>
                                            <td><?= $user->username; ?></td>
                                            <td><?= $user->email; ?></td>
                                            <td><?= $user->date_registered; ?></td>
                                            <td>
                                            <div class="card-footer">
                                            <a href='javascript:PopupCentrer("<?php echo URL_ROOT;?>/users/edit/<?= $user->id_user; ?>",500,750,"menubar=no,scrollbars=no,statusbar=no")'
            								class="btn btn-primary">Modifier</a>
                                            <form action="<?= URL_ROOT;?>/users/delete/<?= $user->id_user; ?>" method="post">
                                            <button type="submit" class="btn btn-danger btn-sm">Supprimer</button>
                                            </form>

                                            </div>
                                            </td>
                                        </tr>
                                        <?php endforeach;?>
                                    </tbody>
              </table>
          </div>
        </div>
      </div>
