<div class="col-lg-12">
        <div class="panel panel-default">
          <div class="panel-heading">Users</div>
          <div class="panel-body">
            <a href="<?= URL_ROOT;?>/users/add"
            class="btn btn-primary">New</a>
              <table data-toggle="table" data-url=""  data-show-refresh="true" data-show-toggle="true"
              data-show-columns="true" data-search="true" data-select-item-name="toolbar1" data-pagination="true"
              data-sort-name="name" data-sort-order="desc">
              <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Username :</th>
                                            <th>Created at</th>
                                            <th>Options</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach ($data['users'] as $user) :?>
                                        <tr>
                                            <td><?= $user->user_id; ?> </td>
                                            <td><?= $user->username; ?></td>
                                            <td><?= $user->created_at; ?></td>
                                            <td>
                                            <div class="card-footer">
                                            <a href="<?= URL_ROOT;?>/users/edit/<?= $user->user_id; ?>"
            								                class="btn btn-primary">Edit</a>
                                            <form action="<?= URL_ROOT;?>/users/delete/<?= $user->user_id; ?>" method="post">
                                            <button type="submit" onclick="return confirm('Are you sure you want to delete this user')" class="btn btn-danger btn-sm">Delete</button>
                                            </form>

                                            </div>
                                            </td>
                                        </tr>
                                        <?php endforeach;?>
                                    </tbody>
              </table>
          </div>
        </div>
      </div>
