    		<div class="row">
    			<div class="col-lg-12">
    				<h1 class="page-header">Accueil</h1>
    			</div>
    		</div><!--/.row-->
			<?php if ($_SESSION['nom_profil'] == "Admin") : ?>
			<div class="col-xs-12 col-md-6 col-lg-3">
				<a href="<?= URL_ROOT;?>/shifts">
				<div class="panel panel-orange panel-widget">
					<div class="row no-padding">
						<div class="col-sm-3 col-lg-5 widget-left">
							<svg class="glyph table"><use xlink:href="#stroked-table"></use></svg>
						</div>
						<div class="col-sm-9 col-lg-7 widget-right">
							<div class="text-muted">Shifts</div>
						</div>
					</div>
				</div>
					</a>
			</div>
			<script type="text/javascript">
			</script>
			<div class="col-xs-12 col-md-6 col-lg-3">
				<a href="<?= URL_ROOT;?>/pauses">
				<div class="panel panel-teal panel-widget">
					<div class="row no-padding">
						<div class="col-sm-3 col-lg-5 widget-left">
							<svg class="glyph stroked calendar"><use xlink:href="#stroked-calendar"></use></svg>
						</div>
						<div class="col-sm-9 col-lg-7 widget-right">
							<div class="text-muted">Pauses</div>
						</div>
					</div>
				</div>
				</a>
			</div>
			<div class="col-xs-12 col-md-6 col-lg-3">
				<a href="<?= URL_ROOT;?>/days_off">
				<div class="panel panel-blue panel-widget ">
					<div class="row no-padding">
						<div class="col-sm-3 col-lg-5 widget-left">
							<svg class="glyph stroked clock"><use xlink:href="#stroked-clock"></use></svg>
						</div>
						<div class="col-sm-9 col-lg-7 widget-right">
							<div class="text-muted">Days-off</div>
						</div>
					</div>
				</div>
				</a>
			</div>
			<div class="col-xs-12 col-md-6 col-lg-3">
				<a href="<?= URL_ROOT;?>/users/profile">
					<div class="panel panel-red panel-widget">
					<div class="row no-padding">
						<div class="col-sm-3 col-lg-5 widget-left">
							<svg class="glyph stroked male user"><use xlink:href="#stroked-male-user"></use></svg>
						</div>
						<div class="col-sm-9 col-lg-7 widget-right">
							<div class="text-muted">Profil</div>
						</div>
					</div>
				</div>
				</a>
			</div>
			<?php elseif($_SESSION['nom_profil'] == "Agent") : ?>
			<div class="col-xs-12 col-md-6 col-lg-3">
				<a href="<?= URL_ROOT;?>/shifts/user">
				<div class="panel panel-orange panel-widget">
					<div class="row no-padding">
						<div class="col-sm-3 col-lg-5 widget-left">
							<svg class="glyph table"><use xlink:href="#stroked-table"></use></svg>
						</div>
						<div class="col-sm-9 col-lg-7 widget-right">
							<div class="text-muted">Shift</div>
						</div>
					</div>
				</div>
					</a>
			</div>
			<div class="col-xs-12 col-md-6 col-lg-3">
				<a href="<?= URL_ROOT;?>/pauses/user">
				<div class="panel panel-teal panel-widget">
					<div class="row no-padding">
						<div class="col-sm-3 col-lg-5 widget-left">
							<svg class="glyph stroked calendar"><use xlink:href="#stroked-calendar"></use></svg>
						</div>
						<div class="col-sm-9 col-lg-7 widget-right">
							<div class="text-muted">Pauses</div>
						</div>
					</div>
				</div>
				</a>
			</div>
			<div class="col-xs-12 col-md-6 col-lg-3">
				<a href="<?= URL_ROOT;?>/days_off/user">
				<div class="panel panel-blue panel-widget ">
					<div class="row no-padding">
						<div class="col-sm-3 col-lg-5 widget-left">
							<svg class="glyph stroked clock"><use xlink:href="#stroked-clock"></use></svg>
						</div>
						<div class="col-sm-9 col-lg-7 widget-right">
							<div class="text-muted">Days-off</div>
						</div>
					</div>
				</div>
				</a>
			</div>
			<div class="col-xs-12 col-md-6 col-lg-3">
				<a href="<?= URL_ROOT;?>/users/profile">
					<div class="panel panel-red panel-widget">
					<div class="row no-padding">
						<div class="col-sm-3 col-lg-5 widget-left">
							<svg class="glyph stroked male user"><use xlink:href="#stroked-male-user"></use></svg>
						</div>
						<div class="col-sm-9 col-lg-7 widget-right">
							<div class="text-muted">Profil</div>
						</div>
					</div>
				</div>
				</a>
			</div>
		<?php endif;?>