<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading">Add an order</div>
        <div class="panel-body">
            <div class="col-md-6">
                <form role="form" action="<?= URL_ROOT; ?>/orders/add" method="post">
                    <div class="form-group">
                        <label>Customer name :</label>
                        <select name="customer_id"
                                class="form-control <?= (!empty($data['customer_id_err'])) ? 'is-invalid' : ''; ?>">
                            <option value=""></option>
                            <?php foreach ($data['customers'] as $customer) : ?>
                                <option value="<?= $customer->id; ?>"><?= $customer->first_name . " " . $customer->last_name; ?></option>
                            <?php endforeach; ?>
                        </select>
                        <span class="invalid-feedback"><?= $data['customer_id_err'] ?></span>
                    </div>
                    <div class="form-group">
                        <label>Categories :</label>
                        <select name="cat_id" id="cat_id"
                                class="form-control <?= (!empty($data['cat_id_err'])) ? 'is-invalid' : ''; ?>">
                            <option value="">Select a category</option>
                            <?php foreach ($data['categories'] as $category) : ?>
                                <option value="<?php echo $category->id; ?>"><?php echo $category->cat_name; ?></option>
                            <?php endforeach; ?>
                        </select>
                        <span class="invalid-feedback"><?= $data['cat_id_err'] ?></span>
                    </div>
                    <div class="form-group">
                        <label>Products :</label>
                        <select name="product_id" id="product_id"
                                class="form-control <?= (!empty($data['product_id_err'])) ? 'is-invalid' : ''; ?>">
                            <option value="">Select a product</option>
                        </select>
                        <span class="invalid-feedback"><?= $data['product_id_err'] ?></span>
                    </div>
                    <div class="form-group">
                        <label for="unit_price">Unit price :</label>
                        <input type="text" name="unit_price" id="unit_price"
                               class="form-control <?= (!empty($data['unit_price_err'])) ? 'is_invalid' : ''; ?>"
                               placeholder="" value="">
                        <span class="invalid-feedback"><?= $data['unit_price_err'] ?></span>
                    </div>
                    <div class="form-group">
                        <label>qty :</label>
                        <input type="text" name="qty" id="qty"
                               class="form-control <?= (!empty($data['qty_err'])) ? 'is_invalid' : ''; ?>"
                               placeholder="" value="<?= $data['qty']; ?>">
                        <span class="invalid-feedback"><?= $data['qty_err'] ?></span>
                    </div>
                    <div class="form-group">
                        <label>Total :</label>
                        <input type="text" name="total" id="total"
                               class="form-control <?= (!empty($data['total_err'])) ? 'is_invalid' : ''; ?>"
                               placeholder="" value="<?= $data['total']; ?>">
                        <span class="invalid-feedback"><?= $data['total_err'] ?></span>
                    </div>
                    <script>
                        $(function () {
                            alert($('#qty').val());
                        });
                    </script>
                    <button type="submit" id="submit" class="btn btn-primary">Save</button>
                    <button type="reset" class="btn btn-default">Reset</button>
                </form>
            </div>
        </div>
    </div>
</div><!-- /.col-->