<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Gestion shift | Econet-Leo</title>

<link href="<?= URL_ROOT;?>/css/bootstrap.min.css" rel="stylesheet">
<link href="<?= URL_ROOT;?>/css/datepicker3.css" rel="stylesheet">
<link href="<?= URL_ROOT;?>/css/bootstrap-table.css" rel="stylesheet">
<link href="<?= URL_ROOT;?>/css/styles.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="<?= URL_ROOT;?>/css/fontawesome.min.css">

<!--Icons-->
<script src="<?= URL_ROOT;?>/js/lumino.glyphs.js"></script>

<!--[if lt IE 9]>
<script src="js/html5shiv.js"></script>
<script src="js/respond.min.js"></script>
<![endif]-->

</head>
