<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="<?= URL_ROOT;?>"><span>PHP-MVC-TUTORIAL |</span> Simple Sotre Management</a>
				<ul class="user-menu">
					<li class="dropdown pull-right">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> <?php //echo $_SESSION['username']; ?> <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="<?= URL_ROOT;?>/users/profile"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> 
							<?= $_SESSION['username']; ?></a></li>
							<li><a href="<?= URL_ROOT;?>/users/login"><svg class="glyph stroked cancel"><use xlink:href="#stroked-cancel"></use></svg> Deconnexion</a></li>
						</ul>
					</li>
				</ul>
			</div>
							
		</div><!-- /.container-fluid -->
	</nav>